server:
  port: 10086
spring:
  application:
    name: supergo-eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true #不注册自己到eureka server
    fetch-registry: false # 不拉去其他微服务列表
  server:
      enable-self-preservation: false #关闭自我保护
      eviction-interval-timer-in-ms: 10000 #剔除失效微服务的轮询间隔时间


