server:
  port: 9003
spring:
  application:
    name: supergo-search
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/supergo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      #      filters: stat,wall,log4j,config  # stat是统计，wall是SQL防火墙，防SQL注入的，log4j是用来输出统计数据的
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow: 127.0.0.1 #IP 白名单
        url-pattern: /druid/* #监控地址,默认 /druid/*
        login-username: admin
        login-password: admin
  #        deny:IP 黑名单
  data:
    elasticsearch:
      cluster-name: my-elasticsearch
      cluster-nodes: 192.168.220.100:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
management:
  endpoint:
    shutdown:
      enabled: true #开启端点
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.supergo: debug
